//
//  GhostingApp.swift
//  Shared
//
//  Created by Elisabeth Whiteley on 16/03/2022.
//

import SwiftUI

class GhostSettings: ObservableObject {

    @Published var isMale: Bool?
    @Published var ghostOrbSize: String? // smaller = been ghost for longer
    @Published var ageRange: String?
    @Published var voice: String? // louder = more angry personality type
    @Published var distortion: String? // more distortion = more violent death
    @Published var chosenGhost: String = ""
    @Published var ghosts: [Ghost]
    @Published var possibleGhosts: [Ghost]
    @Published var ghostBluetoothObject: String = "Elisabeths AirPods Pro"
    @Published var longitude = 5.309672
    @Published var latitude = 60.4340887

    init(isMale: Bool?, ghostOrbSize: String?, ageRange: String?, voice: String?, distortion: String?, chosenGhost: String, ghosts: [Ghost], possibleGhosts: [Ghost]) {
        self.isMale = isMale
        self.ghostOrbSize = ghostOrbSize
        self.ageRange = ageRange
        self.voice = voice
        self.distortion = distortion
        self.chosenGhost = chosenGhost
        self.ghosts = ghosts
        self.possibleGhosts = possibleGhosts
    }
}


@main
struct GhostingApp: App {
    var data = Data()
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        WindowGroup {
            ContentView().environmentObject(GhostSettings(isMale: nil, ghostOrbSize: nil, ageRange: nil, voice: nil, distortion: nil, chosenGhost: "", ghosts: [ Ghost(id: "1", name: "Margaret Carter", age: 82, disposition: "Happy", violentDeath: false, yearOfDeath: 1999, isMale: false, isHere: false, description: "Cause of death: lung cancer. Her family mourn the death of their matriarch, describing her as strong and opinionated but fair and compassionate.",  voice: "Whisper", ghostOrbSize: "Large", distortionLevel: "None", ageRange: "Senior (60+)"),
                                                                                                                                                                 Ghost(id: "2", name: "Trevor Bartlet", age: 47, disposition: "Angry", violentDeath: false, yearOfDeath: 1924, isMale: true, isHere: false, description: "Was at a bar, stepped into road and got hit by a car. Dead instantly. Friends say drunk at time of death, left bar in good mood. \n - Granddaughter called him nice, but quick to anger. Had issues with his boss.  \n Favorite things: baseball.", voice: "Loud", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "3",name: "Sarah Peterson", age: 29, disposition: "Angry", violentDeath: false, yearOfDeath: 1697, isMale: false, isHere: false, description: "Suffering from many illnesses since she was a young child left Sarah without friends. As an adult she was married off to the third son of a baker, who died mysteriously shortly after. She finally succumbed to her illnesses and died at her home before turning 30.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "None", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "4",name: "Dmitri Kalinski", age: 19, disposition: "Angry", violentDeath: true, yearOfDeath: 1989, isMale: true, isHere: false, description: "5 GSW to the chest, shot at close range. Family say nothing except show pictures of him as a boy. \n Profession: Unemployed (russian mob?) \n  Favorite things: pocket knife, ex girlfriend Beatrice.", voice: "Loud", ghostOrbSize: "Large", distortionLevel: "High", ageRange: "Young adult (12-24)" ),
                                                                                                                                                                 Ghost(id: "5",name: "Joshua Tibble", age: 10, disposition: "Angry", violentDeath: true, yearOfDeath: 1856, isMale: true, isHere: false, description: "Cause of death: stabbed by his mother when she found him strangling his little sister to death, \n Favorite things: unknown.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Child (<12)"),
                                                                                                                                                                 Ghost(id: "6",name: "Jennie Tibble", age: 4, disposition: "Happy", violentDeath: true, yearOfDeath: 1856, isMale: false, isHere: false, description: "Cause of death: strangled to death by her older brother, \n Favorite things: her siblings, dolls.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Child (<12)" ),
                                                                                                                                                                 Ghost(id: "7",name: "Betsy Woolward", age: 32, disposition: "Ok", violentDeath: true, yearOfDeath: 1982, isMale: false, isHere: false, description: "Stabbed to death by husband (Atticus) during dispute.  \n Domestic violence reports dating back to the beginning of their 13 year marriage.  \n - Friends say she was sweet, always helpful, never a bad word to say about anyone. \n Favorite things: tea, bunnies.", voice: "Normal", ghostOrbSize: "Large", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "8",name: "Caroline Binksley", age: 15, disposition: "Ok", violentDeath: true, yearOfDeath: 1757, isMale: false, isHere: false, description: "Cause of death: jumped off a bridge when her parents married her off to an older man.  \n - Not much is known about her except that her family was very poor, and she was considered the village beauty, known for her long locks of red hair", voice: "Normal", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Young adult (12-24)" ),
                                                                                                                                                                 Ghost(id: "9",name: "Ballie ??", age: 64, disposition: "Ok", violentDeath: false, yearOfDeath: 1934, isMale: true, isHere: false, description: "Homeless, often stayed outside the establishments on or near this street. Very little known. Perhaps former military? \n Favorite things: food, money, alcohol.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Senior (60+)" ),
                                                                                                                                                                 Ghost(id: "10",name: "Calen Heckell", age: 59, disposition: "Ok", violentDeath: false, yearOfDeath: 1903, isMale: true, isHere: false, description: "Cause of death: tuberculosis. Sick for a long time. \n Profession: Professor of Medicine \n Left behind 2 kids (Mark, 23, and Mary, 15). Wife died in childbirth with Mary.  \n Favorite things: children, golf.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "11",name: "Jack Parker", age: 24, disposition: "Happy", violentDeath: true, yearOfDeath: 1896, isMale: true, isHere: false, description: "A wealthy young man, but compassionate and naive. Found bound and gagged at his house with a slit throat, which had been robbed of everything but the wallpaper.  \n Favorite things: card games, the outdoors.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Young adult (12-24)" ),
                                                                                                                                                                 Ghost(id: "12",name: "Mina Beltram", age: 35, disposition: "Happy", violentDeath: true, yearOfDeath: 1553, isMale: false, isHere: true, description: "After the death of her children due to a sickness spreading through her village, it is said she stopped attending church. \n She denounced God publicly, and for this she was slowly tortured over many days until she confessed to being a witch, at which point she burned at the stake.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Adult (25-59)"),
                                                                                                                                                Ghost(id: "13",name: "Maggie Lockley", age: 7, disposition: "Ok", violentDeath: true, yearOfDeath: 1924, isMale: false, isHere: false, description: "Cause of death: drowned? Unclear. \n Family had 6 children, 4 of whom died early in suspicious circumstances. \n Alcoholic mother?? \n Father owned apothecary, family lived in apartment above it.  \n Favorite things: blanket, family dog, sweets.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "High", ageRange: "Child (<12)" ),
                                                                                                                                                                 Ghost(id: "14",name: "John Lugosi", age: 34, disposition: "Ok", violentDeath: true, yearOfDeath: 1969, isMale: true, isHere: false, description: "Cause of death: accidentally shot by his brother, bled out slowly while the ambulance took too long to get to them due to the snowstorm. \n His friends say: dont bring guns to bachelor parties. \n Favorite things: his brother and friends", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "15",name: "Jared Lugosi", age: 75, disposition: "Angry", violentDeath: false, yearOfDeath: 2009, isMale: true, isHere: false, description: "Cause of death: died peacefully in his sleep. Despite losing his brother to an accident as a young man, he did well for himself and didnt let it affect him. He is described as an impressive marksman. \n Favorite things: his gun collection", voice: "Loud", ghostOrbSize: "Large", distortionLevel: "None", ageRange: "Senior (60+)" ),
                                                                                                                                                                 Ghost(id: "16",name: "Maria Shelley", age: 47, disposition: "Angry", violentDeath: true, yearOfDeath: 1899, isMale: false, isHere: false, description: "Rumor had it that Maria Shelley was a serial killer, but it was never proved. Maria was a prostitute, and it was believed that her victims were johns that tried to do more than had been agreed upon. She was found dead in her bed, stabbed 31 times in the chest, perhaps by a would-be victim?.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "17", name: "Martin Schlott", age: 39, disposition: "Angry", violentDeath: true, yearOfDeath: 1677, isMale: true, isHere: false, description: "A tailor for the rich, and a strict authoritarian at home. His wife and children would often be seen about town with black eyes, a broken nose or other signs of beatings. He was found bound to his bed with his skin partially flayed and his eyes and hands missing, his family missing.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                                                                                                                                                                 Ghost(id: "18", name: "Morgan Bell", age: 5, disposition: "Ok", violentDeath: false, yearOfDeath: 1905, isMale: true, isHere: false, description: "Cause of death: influenza, died alone during the night. \n Rich family, owns a lot of land. Mother says child was always content. Nanny says otherwise (bullied by older siblings). \n Favorite things: teddy, apples.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Child (<12)" ),
                                                                                                                                                                 Ghost(id: "19", name: "Anna Marsh", age: 21, disposition: "Ok", violentDeath: false, yearOfDeath: 2001, isMale: false, isHere: false, description: "Cause of death: aggressive breast cancer. \n Anna was studying medicine when she fell ill and died only weeks later. She is described by family and friends as bright, funny and full of life.  \n Favorite things: hot chocolate.", voice: "Normal", ghostOrbSize: "Large", distortionLevel: "None", ageRange: "Young adult (12-24)" ),
                                                                                                                                                                 Ghost(id: "20", name: "Maia Bateman", age: 41, disposition: "Ok", violentDeath: false, yearOfDeath: 1908, isMale: false, isHere: false, description: "Cause of death: unknown sickness, she died in her bed of a fever with her family by her side.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Adult (25-59)" ),Ghost(id: "21",name: "Fiona Partham", age: 35, disposition: "Happy", violentDeath: false, yearOfDeath: 1631, isMale: false, isHere: false, description: "Cause of death: tuberculosis. The daughter of a wealthy mayor, she never married, however, her gravestone describes her as 'The greatest joy is that which you make for yourself'. She left behind 14 cats and a dog.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "None", ageRange: "Adult (25-59)"),], possibleGhosts: [
                Ghost(id: "1", name: "Margaret Carter", age: 82, disposition: "Happy", violentDeath: false, yearOfDeath: 1999, isMale: false, isHere: false, description: "Cause of death: lung cancer. Her family mourn the death of their matriarch, describing her as strong and opinionated but fair and compassionate.",  voice: "Whisper", ghostOrbSize: "Large", distortionLevel: "None", ageRange: "Senior (60+)"),
                Ghost(id: "2", name: "Trevor Bartlet", age: 47, disposition: "Angry", violentDeath: false, yearOfDeath: 1924, isMale: true, isHere: false, description: "Was at a bar, stepped into road and got hit by a car. Dead instantly. Friends say drunk at time of death, left bar in good mood. \n - Granddaughter called him nice, but quick to anger. Had issues with his boss.  \n Favorite things: baseball.", voice: "Loud", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Adult (25-59)" ),
                Ghost(id: "3",name: "Sarah Peterson", age: 29, disposition: "Angry", violentDeath: false, yearOfDeath: 1697, isMale: false, isHere: false, description: "Suffering from many illnesses since she was a young child left Sarah without friends. As an adult she was married off to the third son of a baker, who died mysteriously shortly after. She finally succumbed to her illnesses and died at her home before turning 30.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "None", ageRange: "Adult (25-59)" ),
                Ghost(id: "4",name: "Dmitri Kalinski", age: 19, disposition: "Angry", violentDeath: true, yearOfDeath: 1989, isMale: true, isHere: false, description: "5 GSW to the chest, shot at close range. Family say nothing except show pictures of him as a boy. \n Profession: Unemployed (russian mob?) \n  Favorite things: pocket knife, ex girlfriend Beatrice.", voice: "Loud", ghostOrbSize: "Large", distortionLevel: "High", ageRange: "Young adult (12-24)" ),
                Ghost(id: "5",name: "Joshua Tibble", age: 10, disposition: "Angry", violentDeath: true, yearOfDeath: 1856, isMale: true, isHere: false, description: "Cause of death: stabbed by his mother when she found him strangling his little sister to death, \n Favorite things: unknown.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Child (<12)"),
                Ghost(id: "6",name: "Jennie Tibble", age: 4, disposition: "Happy", violentDeath: true, yearOfDeath: 1856, isMale: false, isHere: false, description: "Cause of death: strangled to death by her older brother, \n Favorite things: her siblings, dolls.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Child (<12)" ),
                Ghost(id: "7",name: "Betsy Woolward", age: 32, disposition: "Ok", violentDeath: true, yearOfDeath: 1982, isMale: false, isHere: false, description: "Stabbed to death by husband (Atticus) during dispute.  \n Domestic violence reports dating back to the beginning of their 13 year marriage.  \n - Friends say she was sweet, always helpful, never a bad word to say about anyone.  \n Favorite things: tea, bunnies.", voice: "Normal", ghostOrbSize: "Large", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                Ghost(id: "8",name: "Caroline Binksley", age: 15, disposition: "Ok", violentDeath: true, yearOfDeath: 1757, isMale: false, isHere: false, description: "Cause of death: jumped off a bridge when her parents married her off to an older man.  \n - Not much is known about her except that her family was very poor, and she was considered the village beauty, known for her long locks of red hair", voice: "Normal", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Young adult (12-24)" ),
                Ghost(id: "9",name: "Ballie ??", age: 64, disposition: "Ok", violentDeath: false, yearOfDeath: 1934, isMale: true, isHere: false, description: "Homeless, often stayed outside the establishments on or near this street. Very little known. Perhaps former military? \n Favorite things: food, money, alcohol.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Senior (60+)" ),
                Ghost(id: "10",name: "Calen Heckell", age: 59, disposition: "Ok", violentDeath: false, yearOfDeath: 1903, isMale: true, isHere: false, description: "Cause of death: tuberculosis. Sick for a long time. \n Profession: Professor of Medicine \n Left behind 2 kids (Mark, 23, and Mary, 15). Wife died in childbirth with Mary.  \n Favorite things: children, golf.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Adult (25-59)" ),
                Ghost(id: "11",name: "Jack Parker", age: 24, disposition: "Happy", violentDeath: true, yearOfDeath: 1896, isMale: true, isHere: false, description: "A wealthy young man, but compassionate and naive. Found bound and gagged at his house with a slit throat, which had been robbed of everything but the wallpaper.  \n Favorite things: card games, the outdoors.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Young adult (12-24)" ),
                Ghost(id: "12",name: "Mina Beltram", age: 35, disposition: "Happy", violentDeath: true, yearOfDeath: 1603, isMale: false, isHere: true, description: "After the death of her children due to a sickness spreading through her village, it is said she stopped attending church. \n She denounced God publicly, and for this she was slowly tortured over many days until she confessed to being a witch, at which point she burned at the stake.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Adult (25-59)"),
                Ghost(id: "13",name: "Maggie Lockley", age: 7, disposition: "Ok", violentDeath: true, yearOfDeath: 1924, isMale: false, isHere: false, description: "Cause of death: drowned? Unclear. \n Family had 6 children, 4 of whom died early in suspicious circumstances. \n Alcoholic mother?? \n Father owned apothecary, family lived in apartment above it.  \n Favorite things: blanket, family dog, sweets.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "High", ageRange: "Child (<12)" ),
                Ghost(id: "14",name: "John Lugosi", age: 34, disposition: "Ok", violentDeath: true, yearOfDeath: 1969, isMale: true, isHere: false, description: "Cause of death: accidentally shot by his brother, bled out slowly while the ambulance took too long to get to them due to the snowstorm. \n His friends say: dont bring guns to bachelor parties. \n Favorite things: his brother and friends", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                Ghost(id: "15",name: "Jared Lugosi", age: 75, disposition: "Angry", violentDeath: false, yearOfDeath: 2009, isMale: true, isHere: false, description: "Cause of death: died peacefully in his sleep. Despite losing his brother to an accident as a young man, he did well for himself and didnt let it affect him. He is described as an impressive marksman. \n Favorite things: his gun collection", voice: "Loud", ghostOrbSize: "Large", distortionLevel: "None", ageRange: "Senior (60+)" ),
                Ghost(id: "16",name: "Maria Shelley", age: 47, disposition: "Angry", violentDeath: true, yearOfDeath: 1899, isMale: false, isHere: false, description: "Rumor had it that Maria Shelley was a serial killer, but it was never proved. Maria was a prostitute, and it was believed that her victims were johns that tried to do more than had been agreed upon. She was found dead in her bed, stabbed 31 times in the chest, perhaps by a would-be victim?.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                Ghost(id: "17", name: "Martin Schlott", age: 39, disposition: "Angry", violentDeath: true, yearOfDeath: 1677, isMale: true, isHere: false, description: "A tailor for the rich, and a strict authoritarian at home. His wife and children would often be seen about town with black eyes, a broken nose or other signs of beatings. He was found bound to his bed with his skin partially flayed and his eyes and hands missing, his family missing.", voice: "Loud", ghostOrbSize: "Small", distortionLevel: "High", ageRange: "Adult (25-59)" ),
                Ghost(id: "18", name: "Morgan Bell", age: 5, disposition: "Ok", violentDeath: false, yearOfDeath: 1905, isMale: true, isHere: false, description: "Cause of death: influenza, died alone during the night. \n Rich family, owns a lot of land. Mother says child was always content. Nanny says otherwise (bullied by older siblings). \n Favorite things: teddy, apples.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Child (<12)" ),
                Ghost(id: "19", name: "Anna Marsh", age: 21, disposition: "Ok", violentDeath: false, yearOfDeath: 2001, isMale: false, isHere: false, description: "Cause of death: aggressive breast cancer. \n Anna was studying medicine when she fell ill and died only weeks later. She is described by family and friends as bright, funny and full of life.  \n Favorite things: hot chocolate.", voice: "Normal", ghostOrbSize: "Large", distortionLevel: "None", ageRange: "Young adult (12-24)" ),
                Ghost(id: "20", name: "Maia Bateman", age: 41, disposition: "Ok", violentDeath: false, yearOfDeath: 1908, isMale: false, isHere: false, description: "Cause of death: unknown sickness, she died in her bed of a fever with her family by her side.", voice: "Normal", ghostOrbSize: "Medium", distortionLevel: "None", ageRange: "Adult (25-59)"),
                Ghost(id: "21",name: "Fiona Partham", age: 35, disposition: "Happy", violentDeath: false, yearOfDeath: 1631, isMale: false, isHere: false, description: "Cause of death: tuberculosis. The daughter of a wealthy mayor, she never married, however, her gravestone describes her as 'The greatest joy is that which you make for yourself'. She left behind 14 cats and a dog.", voice: "Whisper", ghostOrbSize: "Small", distortionLevel: "None", ageRange: "Adult (25-59)"),
            ]))
        }
    }
}

struct GhostingApp_Previews: PreviewProvider {
    static var previews: some View {
        /*@START_MENU_TOKEN@*/Text("Hello, World!")/*@END_MENU_TOKEN@*/
    }
}

class AppDelegate: NSObject, UIApplicationDelegate {
    
    static var orientationLock = UIInterfaceOrientationMask.all
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        // something to do
        return true
    }
    
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window:UIWindow?) -> UIInterfaceOrientationMask {
        return AppDelegate.orientationLock
    }
}
